// Generate .lastgood/verified-context.md — a strictly factual handoff for an AI
// coding agent (Claude Code / Cursor / Copilot / Codex). Every line is a detected
// fact with provenance; the file explicitly draws no conclusions about causes, so
// the agent reasons from evidence instead of hallucinating.

import type { Finding, Fingerprint, Severity } from './types.js'

export function generateContext(lastGood: Fingerprint, current: Fingerprint, findings: Finding[]): string {
  const out: string[] = []
  const successNote = lastGood.success
    ? `${lastGood.trigger}, \`${lastGood.success.command}\` exit ${lastGood.success.exitCode}`
    : lastGood.trigger

  out.push('# Verified Project Context — generated by LastGood (facts only, no inference)')
  out.push(`Generated: ${current.createdAt} · Last-good: ${lastGood.createdAt} (${successNote})`, '')

  // Environment
  out.push('## Environment (verified this run)')
  out.push(`- OS: ${current.machine.os} ${current.machine.arch}`)
  const runtimes = new Set([...Object.keys(current.runtimes), ...Object.keys(lastGood.runtimes)])
  for (const rt of runtimes) {
    const now = current.runtimes[rt as keyof typeof current.runtimes]
    const then = lastGood.runtimes[rt as keyof typeof lastGood.runtimes]
    if (!now && !then) continue
    const changed = now && then && now !== then ? '   ← CHANGED' : ''
    out.push(`- ${rt}: ${now ?? 'not found'}${then && then !== now ? ` (last-good: ${then})` : ''}${changed}`)
  }
  out.push('')

  // Changes
  out.push('## What changed since the project last worked')
  if (findings.length === 0) {
    out.push('- Nothing changed. The environment matches the last-good state.', '')
  } else {
    for (const sev of ['blocking', 'likely', 'nice'] as Severity[]) {
      const items = findings.filter((f) => f.severity === sev)
      if (!items.length) continue
      out.push(`${sev.toUpperCase()}:`)
      for (const f of items) {
        const fix = f.fix?.command ? `  Fix: \`${f.fix.command}\`` : ''
        out.push(`- ${f.title}.${fix}`)
      }
    }
    out.push('')
  }

  // Config keys
  if (current.envSchema.keys.length) {
    out.push('## Expected configuration keys (names only — values NOT stored)')
    out.push(current.envSchema.keys.join(', '))
    const added = current.envSchema.keys.filter((k) => !lastGood.envSchema.keys.includes(k))
    if (added.length) out.push(`- New since last-good (need a local value): ${added.join(', ')}   ← BLOCKING`)
    out.push('')
  }

  // Services
  if (current.dockerServices.length) {
    out.push('## Services (docker compose, declared)')
    for (const s of current.dockerServices) out.push(`- ${s}`)
    out.push('')
  }

  // Ground truth
  out.push('## Ground truth')
  if (lastGood.success) {
    out.push(`- "Working" is defined as: \`${lastGood.success.command}\` exits 0 (last verified ${lastGood.success.ranAt}).`)
  } else {
    out.push('- Last-good state was recorded manually with `lastgood mark`.')
  }
  out.push('- This file contains only detected facts. It draws no conclusions about causes.', '')

  return out.join('\n')
}
